import js from "@eslint/js";
import prettier from "eslint-plugin-prettier";
import prettierConfig from "eslint-config-prettier";

export default [
    { ignores: ["eslint.config.mjs"] },
    js.configs.recommended,
    prettierConfig,
    {
        plugins: {
            prettier,
        },
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "script",
            globals: {
                // KubeJS globals
                event: "readonly",
                global: "writable",
                Item: "readonly",
                Ingredient: "readonly",
                Fluid: "readonly",
                AABB: "readonly",
                BlockPos: "readonly",
                Vec3: "readonly",
                UUID: "readonly",
                Java: "readonly",
                Platform: "readonly",
                console: "readonly",
                Text: "readonly",
                Component: "readonly",
                Color: "readonly",
                JEIEvents: "readonly",
                ItemEvents: "readonly",
                FluidEvents: "readonly",
                BlockEvents: "readonly",
                EntityEvents: "readonly",
                PlayerEvents: "readonly",
                WorldEvents: "readonly",
                ServerEvents: "readonly",
                ClientEvents: "readonly",
                Ponder: "readonly",
                ponderScenes: "writable",
                $MultiblockMachineDefinition: "readonly",
                GTRegistries: "readonly",
                GTValues: "readonly",
                GTRecipeCategories: "readonly",
                CleanroomType: "readonly",
                $StarTAbyssalContainmentMachine: "readonly",
                GTCEuServerEvents: "readonly",
                LootJS: "readonly",
                GTMaterials: "readonly",
                Block: "readonly",
                JSONObject: "readonly",
                FluidIngredientJS: "readonly",
                LootEntry: "readonly",
                JavaMath: "readonly",
                Utils: "readonly",
                GTMaterialFlags: "readonly",
                PropertyKey: "readonly",
                $StarTAbyssalContainmentMachine: "readonly",
                GTCEuStartupEvents: "readonly",
                GTElements: "readonly",
                GTMaterialIconSet: "readonly",
                IngotProperty: "readonly",
                DustProperty: "readonly",
                FluidProperty: "readonly",
                GTFluidStorageKeys: "readonly",
                GTFluidBuilder: "readonly",
                BlastProperty: "readonly",
                $FluidHatchPartMachine: "readonly",
                $GTMachineModelProperties: "readonly",
                $CleaningMaintenanceHatchPartMachine: "readonly",
                RotationState: "readonly",
                PartAbility: "readonly",
                GTRecipeTypes: "readonly",
                GCYMMachines: "readonly",
                GTRecipeModifiers: "readonly",
                GuiTextures: "readonly",
                GTSoundEntries: "readonly",
                FillDirection: "readonly",
                FactoryBlockPattern: "readonly",
                Predicates: "readonly",
                $CoiledMulti: "readonly",
                $StarTRecipeModifiers: "readonly",
                GCYMBlocks: "readonly",
                GTBlocks: "readonly",
                $StartSteamMulti: "readonly",
                $SteamMulti: "readonly",
                $OpticalComputationMachine: "readonly",
                $LayeredWorkableElectricMultiblockMachine: "readonly",
                $RelativeDirection: "readonly",
                $AssemblyLineMulti: "readonly",
                $StarTDraconicInfusionMachine: "readonly",
                $VacuumChemicalReactorMachine: "readonly",
                $StarTPartAbility: "readonly",
                $KomaruFrameMachine: "readonly",
                StartupEvents: "readonly",
                ToolProperty: "readonly",
                GTToolType: "readonly",
                ForgeEvents: "readonly",
                WorldgenEvents: "readonly",
                $FormattingUtil: "readonly",
                WidgetGroup: "readonly",
                ProgressWidget: "readonly",
            },
        },
        rules: {
            "indent": "off",
            "prettier/prettier": "error",
            camelcase: [
                "error",
                {
                    properties: "always",
                    ignoreDestructuring: false,
                    ignoreImports: false,
                    allow: ["^\\$?[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$"],
                },
            ],
            "id-match": [
                "error",
                "^\\$?([a-z][a-zA-Z0-9]*|[A-Z][A-Z0-9]*(_[A-Z0-9]+)*|\\$[A-Z][a-zA-Z0-9]*|[a-z])$",
                {
                    properties: true,
                    onlyDeclarations: true,
                    ignoreDestructuring: true,
                },
            ],
            "no-var": "error",
            eqeqeq: ["error", "always"],
            "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
            "no-console": "off",
            "no-redeclare": ["error", { "builtinGlobals": false }],
        },
    },
    {
        files: ["kubejs/**/*.js"],
    },
];
