namespace internal.com.gregtechceu.gtceu.common.data {
    import Material = api.data.chemical.material.Material;

    class GTMaterials {
        static CHEMICAL_DYES: Material[];
        static VOLTAGE_COMMON_MATERIALS: Material[];

        static get(key: string): Material;

        static Actinium: Material;
        static Aluminium: Material;
        static Americium: Material;
        static Antimony: Material;
        static Argon: Material;
        static Arsenic: Material;
        static Astatine: Material;
        static Barium: Material;
        static Berkelium: Material;
        static Beryllium: Material;
        static Bismuth: Material;
        static Bohrium: Material;
        static Boron: Material;
        static Bromine: Material;
        static Caesium: Material;
        static Calcium: Material;
        static Californium: Material;
        static Carbon: Material;
        static Cadmium: Material;
        static Cerium: Material;
        static Chlorine: Material;
        static Chromium: Material;
        static Cobalt: Material;
        static Copernicium: Material;
        static Copper: Material;
        static Curium: Material;
        static Darmstadtium: Material;
        static Deuterium: Material;
        static Dubnium: Material;
        static Dysprosium: Material;
        static Einsteinium: Material;
        static Erbium: Material;
        static Europium: Material;
        static Fermium: Material;
        static Flerovium: Material;
        static Fluorine: Material;
        static Francium: Material;
        static Gadolinium: Material;
        static Gallium: Material;
        static Germanium: Material;
        static Gold: Material;
        static Hafnium: Material;
        static Hassium: Material;
        static Holmium: Material;
        static Hydrogen: Material;
        static Helium: Material;
        static Helium3: Material;
        static Indium: Material;
        static Iodine: Material;
        static Iridium: Material;
        static Iron: Material;
        static Krypton: Material;
        static Lanthanum: Material;
        static Lawrencium: Material;
        static Lead: Material;
        static Lithium: Material;
        static Livermorium: Material;
        static Lutetium: Material;
        static Magnesium: Material;
        static Mendelevium: Material;
        static Manganese: Material;
        static Meitnerium: Material;
        static Mercury: Material;
        static Molybdenum: Material;
        static Moscovium: Material;
        static Neodymium: Material;
        static Neon: Material;
        static Neptunium: Material;
        static Nickel: Material;
        static Nihonium: Material;
        static Niobium: Material;
        static Nitrogen: Material;
        static Nobelium: Material;
        static Oganesson: Material;
        static Osmium: Material;
        static Oxygen: Material;
        static Palladium: Material;
        static Phosphorus: Material;
        static Polonium: Material;
        static Platinum: Material;
        static Plutonium239: Material;
        static Plutonium241: Material;
        static Potassium: Material;
        static Praseodymium: Material;
        static Promethium: Material;
        static Protactinium: Material;
        static Radon: Material;
        static Radium: Material;
        static Rhenium: Material;
        static Rhodium: Material;
        static Roentgenium: Material;
        static Rubidium: Material;
        static Ruthenium: Material;
        static Rutherfordium: Material;
        static Samarium: Material;
        static Scandium: Material;
        static Seaborgium: Material;
        static Selenium: Material;
        static Silicon: Material;
        static Silver: Material;
        static Sodium: Material;
        static Strontium: Material;
        static Sulfur: Material;
        static Tantalum: Material;
        static Technetium: Material;
        static Tellurium: Material;
        static Tennessine: Material;
        static Terbium: Material;
        static Thorium: Material;
        static Thallium: Material;
        static Thulium: Material;
        static Tin: Material;
        static Titanium: Material;
        static Tritium: Material;
        static Tungsten: Material;
        static Uranium238: Material;
        static Uranium235: Material;
        static Vanadium: Material;
        static Xenon: Material;
        static Ytterbium: Material;
        static Yttrium: Material;
        static Zinc: Material;
        static Zirconium: Material;
        static Naquadah: Material;
        static NaquadahEnriched: Material;
        static Naquadria: Material;
        static Neutronium: Material;
        static Tritanium: Material;
        static Duranium: Material;
        static Trinium: Material;
        static Almandine: Material;
        static Andradite: Material;
        static AnnealedCopper: Material;
        static Asbestos: Material;
        static Ash: Material;
        static Hematite: Material;
        static BatteryAlloy: Material;
        static BlueTopaz: Material;
        static Bone: Material;
        static Brass: Material;
        static Bronze: Material;
        static Goethite: Material;
        static Calcite: Material;
        static Cassiterite: Material;
        static CassiteriteSand: Material;
        static Chalcopyrite: Material;
        static Charcoal: Material;
        static Chromite: Material;
        static Cinnabar: Material;
        static Water: Material;
        static Coal: Material;
        static Cobaltite: Material;
        static Cooperite: Material;
        static Cupronickel: Material;
        static DarkAsh: Material;
        static Diamond: Material;
        static Electrum: Material;
        static Emerald: Material;
        static Galena: Material;
        static Garnierite: Material;
        static GreenSapphire: Material;
        static Grossular: Material;
        static Ice: Material;
        static Ilmenite: Material;
        static Rutile: Material;
        static Bauxite: Material;
        static Invar: Material;
        static Kanthal: Material;
        static Lazurite: Material;
        static Magnalium: Material;
        static Magnesite: Material;
        static Magnetite: Material;
        static Molybdenite: Material;
        static Nichrome: Material;
        static NiobiumNitride: Material;
        static NiobiumTitanium: Material;
        static Obsidian: Material;
        static Phosphate: Material;
        static SterlingSilver: Material;
        static RoseGold: Material;
        static BlackBronze: Material;
        static BismuthBronze: Material;
        static Biotite: Material;
        static Powellite: Material;
        static Pyrite: Material;
        static Pyrolusite: Material;
        static Pyrope: Material;
        static RockSalt: Material;
        static RTMAlloy: Material;
        static Ruridit: Material;
        static Rubber: Material;
        static Ruby: Material;
        static Salt: Material;
        static Saltpeter: Material;
        static Sapphire: Material;
        static Scheelite: Material;
        static Sodalite: Material;
        static AluminiumSulfite: Material;
        static Tantalite: Material;
        static Coke: Material;
        static Netherite: Material;
        static SolderingAlloy: Material;
        static Spessartine: Material;
        static Sphalerite: Material;
        static StainlessSteel: Material;
        static Steel: Material;
        static Stibnite: Material;
        static Tetrahedrite: Material;
        static TinAlloy: Material;
        static Topaz: Material;
        static Tungstate: Material;
        static Ultimet: Material;
        static Uraninite: Material;
        static Uvarovite: Material;
        static VanadiumGallium: Material;
        static WroughtIron: Material;
        static Wulfenite: Material;
        static Limonite: Material;
        static YellowLimonite: Material;
        static YttriumBariumCuprate: Material;
        static NetherQuartz: Material;
        static CertusQuartz: Material;
        static Quartzite: Material;
        static Graphite: Material;
        static Graphene: Material;
        static TungsticAcid: Material;
        static Osmiridium: Material;
        static LithiumChloride: Material;
        static CalciumChloride: Material;
        static Bornite: Material;
        static Chalcocite: Material;
        static GalliumArsenide: Material;
        static Potash: Material;
        static SodaAsh: Material;
        static IndiumGalliumPhosphide: Material;
        static NickelZincFerrite: Material;
        static SiliconDioxide: Material;
        static MagnesiumChloride: Material;
        static SodiumSulfide: Material;
        static PhosphorusPentoxide: Material;
        static Quicklime: Material;
        static SodiumBisulfate: Material;
        static FerriteMixture: Material;
        static Magnesia: Material;
        static PlatinumGroupSludge: Material;
        static Realgar: Material;
        static SodiumBicarbonate: Material;
        static PotassiumDichromate: Material;
        static ChromiumTrioxide: Material;
        static AntimonyTrioxide: Material;
        static Zincite: Material;
        static CupricOxide: Material;
        static CobaltOxide: Material;
        static ArsenicTrioxide: Material;
        static Massicot: Material;
        static Ferrosilite: Material;
        static MetalMixture: Material;
        static SodiumHydroxide: Material;
        static SodiumPersulfate: Material;
        static Bastnasite: Material;
        static Pentlandite: Material;
        static Spodumene: Material;
        static Lepidolite: Material;
        static GlauconiteSand: Material;
        static Malachite: Material;
        static Mica: Material;
        static Barite: Material;
        static Alunite: Material;
        static Talc: Material;
        static Soapstone: Material;
        static Kyanite: Material;
        static IronMagnetic: Material;
        static TungstenCarbide: Material;
        static CarbonDioxide: Material;
        static TitaniumTetrachloride: Material;
        static NitrogenDioxide: Material;
        static HydrogenSulfide: Material;
        static NitricAcid: Material;
        static SulfuricAcid: Material;
        static PhosphoricAcid: Material;
        static SulfurTrioxide: Material;
        static SulfurDioxide: Material;
        static CarbonMonoxide: Material;
        static HypochlorousAcid: Material;
        static Ammonia: Material;
        static HydrofluoricAcid: Material;
        static NitricOxide: Material;
        static Iron3Chloride: Material;
        static Iron2Chloride: Material;
        static UraniumHexafluoride: Material;
        static EnrichedUraniumHexafluoride: Material;
        static DepletedUraniumHexafluoride: Material;
        static NitrousOxide: Material;
        static EnderPearl: Material;
        static PotassiumFeldspar: Material;
        static NeodymiumMagnetic: Material;
        static HydrochloricAcid: Material;
        static Steam: Material;
        static DistilledWater: Material;
        static SodiumPotassium: Material;
        static SamariumMagnetic: Material;
        static ManganesePhosphide: Material;
        static MagnesiumDiboride: Material;
        static MercuryBariumCalciumCuprate: Material;
        static UraniumTriplatinum: Material;
        static SamariumIronArsenicOxide: Material;
        static IndiumTinBariumTitaniumCuprate: Material;
        static UraniumRhodiumDinaquadide: Material;
        static EnrichedNaquadahTriniumEuropiumDuranide: Material;
        static RutheniumTriniumAmericiumNeutronate: Material;
        static PlatinumRaw: Material;
        static InertMetalMixture: Material;
        static RhodiumSulfate: Material;
        static RutheniumTetroxide: Material;
        static OsmiumTetroxide: Material;
        static IridiumChloride: Material;
        static FluoroantimonicAcid: Material;
        static TitaniumTrifluoride: Material;
        static CalciumPhosphide: Material;
        static IndiumPhosphide: Material;
        static BariumSulfide: Material;
        static TriniumSulfide: Material;
        static ZincSulfide: Material;
        static GalliumSulfide: Material;
        static AntimonyTrifluoride: Material;
        static EnrichedNaquadahSulfate: Material;
        static NaquadriaSulfate: Material;
        static Pyrochlore: Material;
        static PotassiumHydroxide: Material;
        static PotassiumIodide: Material;
        static PotassiumFerrocyanide: Material;
        static CalciumFerrocyanide: Material;
        static CalciumHydroxide: Material;
        static CalciumCarbonate: Material;
        static PotassiumCyanide: Material;
        static PotassiumCarbonate: Material;
        static HydrogenCyanide: Material;
        static FormicAcid: Material;
        static PotassiumSulfate: Material;
        static PrussianBlue: Material;
        static Formaldehyde: Material;
        static Glycolonitrile: Material;
        static DiethylenetriaminePentaacetonitrile: Material;
        static DiethylenetriaminepentaaceticAcid: Material;
        static SodiumNitrite: Material;
        static HydrogenPeroxide: Material;
        static SiliconeRubber: Material;
        static RawRubber: Material;
        static RawStyreneButadieneRubber: Material;
        static StyreneButadieneRubber: Material;
        static PolyvinylAcetate: Material;
        static ReinforcedEpoxyResin: Material;
        static PolyvinylChloride: Material;
        static PolyphenyleneSulfide: Material;
        static GlycerylTrinitrate: Material;
        static Polybenzimidazole: Material;
        static Polydimethylsiloxane: Material;
        static Polyethylene: Material;
        static Epoxy: Material;
        static Polycaprolactam: Material;
        static Polytetrafluoroethylene: Material;
        static Sugar: Material;
        static Methane: Material;
        static Epichlorohydrin: Material;
        static Monochloramine: Material;
        static Chloroform: Material;
        static Cumene: Material;
        static Tetrafluoroethylene: Material;
        static Chloromethane: Material;
        static AllylChloride: Material;
        static Isoprene: Material;
        static Propane: Material;
        static Propene: Material;
        static Ethane: Material;
        static Butene: Material;
        static Butane: Material;
        static DissolvedCalciumAcetate: Material;
        static VinylAcetate: Material;
        static MethylAcetate: Material;
        static Ethenone: Material;
        static Tetranitromethane: Material;
        static Dimethylamine: Material;
        static Dimethylhydrazine: Material;
        static DinitrogenTetroxide: Material;
        static Dimethyldichlorosilane: Material;
        static Styrene: Material;
        static Butadiene: Material;
        static Dichlorobenzene: Material;
        static AceticAcid: Material;
        static Phenol: Material;
        static BisphenolA: Material;
        static VinylChloride: Material;
        static Ethylene: Material;
        static Benzene: Material;
        static Acetone: Material;
        static Glycerol: Material;
        static Methanol: Material;
        static Ethanol: Material;
        static Toluene: Material;
        static DiphenylIsophtalate: Material;
        static PhthalicAcid: Material;
        static Dimethylbenzene: Material;
        static Diaminobenzidine: Material;
        static Dichlorobenzidine: Material;
        static Nitrochlorobenzene: Material;
        static Chlorobenzene: Material;
        static Octane: Material;
        static EthylTertButylEther: Material;
        static Ethylbenzene: Material;
        static Naphthalene: Material;
        static Nitrobenzene: Material;
        static Cyclohexane: Material;
        static NitrosylChloride: Material;
        static CyclohexanoneOxime: Material;
        static Caprolactam: Material;
        static PlatinumSludgeResidue: Material;
        static PalladiumRaw: Material;
        static RarestMetalMixture: Material;
        static AmmoniumChloride: Material;
        static AcidicOsmiumSolution: Material;
        static RhodiumPlatedPalladium: Material;
        static Butyraldehyde: Material;
        static PolyvinylButyral: Material;
        static Biphenyl: Material;
        static PolychlorinatedBiphenyl: Material;
        static AceticAnhydride: Material;
        static AminoPhenol: Material;
        static Paracetamol: Material;
        static AmmoniumFormate: Material;
        static Formamide: Material;
        static WoodGas: Material;
        static WoodVinegar: Material;
        static WoodTar: Material;
        static CharcoalByproducts: Material;
        static Biomass: Material;
        static BioDiesel: Material;
        static FermentedBiomass: Material;
        static Creosote: Material;
        static Diesel: Material;
        static RocketFuel: Material;
        static Glue: Material;
        static Lubricant: Material;
        static McGuffium239: Material;
        static IndiumConcentrate: Material;
        static SeedOil: Material;
        static DrillingFluid: Material;
        static ConstructionFoam: Material;
        static Oil: Material;
        static OilHeavy: Material;
        static RawOil: Material;
        static OilLight: Material;
        static NaturalGas: Material;
        static SulfuricHeavyFuel: Material;
        static HeavyFuel: Material;
        static LightlyHydroCrackedHeavyFuel: Material;
        static SeverelyHydroCrackedHeavyFuel: Material;
        static LightlySteamCrackedHeavyFuel: Material;
        static SeverelySteamCrackedHeavyFuel: Material;
        static SulfuricLightFuel: Material;
        static LightFuel: Material;
        static LightlyHydroCrackedLightFuel: Material;
        static SeverelyHydroCrackedLightFuel: Material;
        static LightlySteamCrackedLightFuel: Material;
        static SeverelySteamCrackedLightFuel: Material;
        static SulfuricNaphtha: Material;
        static Naphtha: Material;
        static LightlyHydroCrackedNaphtha: Material;
        static SeverelyHydroCrackedNaphtha: Material;
        static LightlySteamCrackedNaphtha: Material;
        static SeverelySteamCrackedNaphtha: Material;
        static SulfuricGas: Material;
        static RefineryGas: Material;
        static LightlyHydroCrackedGas: Material;
        static SeverelyHydroCrackedGas: Material;
        static LightlySteamCrackedGas: Material;
        static SeverelySteamCrackedGas: Material;
        static HydroCrackedEthane: Material;
        static HydroCrackedEthylene: Material;
        static HydroCrackedPropene: Material;
        static HydroCrackedPropane: Material;
        static HydroCrackedButane: Material;
        static HydroCrackedButene: Material;
        static HydroCrackedButadiene: Material;
        static SteamCrackedEthane: Material;
        static SteamCrackedEthylene: Material;
        static SteamCrackedPropene: Material;
        static SteamCrackedPropane: Material;
        static SteamCrackedButane: Material;
        static SteamCrackedButene: Material;
        static SteamCrackedButadiene: Material;
        static LPG: Material;
        static RawGrowthMedium: Material;
        static SterileGrowthMedium: Material;
        static Bacteria: Material;
        static BacterialSludge: Material;
        static EnrichedBacterialSludge: Material;
        static Mutagen: Material;
        static GelatinMixture: Material;
        static RawGasoline: Material;
        static Gasoline: Material;
        static HighOctaneGasoline: Material;
        static CoalGas: Material;
        static CoalTar: Material;
        static Gunpowder: Material;
        static Oilsands: Material;
        static RareEarth: Material;
        static Stone: Material;
        static Lava: Material;
        static Glowstone: Material;
        static NetherStar: Material;
        static Endstone: Material;
        static Netherrack: Material;
        static CetaneBoostedDiesel: Material;
        static Collagen: Material;
        static Gelatin: Material;
        static Agar: Material;
        static Andesite: Material;
        static Milk: Material;
        static Cocoa: Material;
        static Wheat: Material;
        static Meat: Material;
        static Wood: Material;
        static TreatedWood: Material;
        static Paper: Material;
        static FishOil: Material;
        static RubySlurry: Material;
        static SapphireSlurry: Material;
        static GreenSapphireSlurry: Material;
        static DyeBlack: Material;
        static DyeRed: Material;
        static DyeGreen: Material;
        static DyeBrown: Material;
        static DyeBlue: Material;
        static DyePurple: Material;
        static DyeCyan: Material;
        static DyeLightGray: Material;
        static DyeGray: Material;
        static DyePink: Material;
        static DyeLime: Material;
        static DyeYellow: Material;
        static DyeLightBlue: Material;
        static DyeMagenta: Material;
        static DyeOrange: Material;
        static DyeWhite: Material;
        static ImpureEnrichedNaquadahSolution: Material;
        static EnrichedNaquadahSolution: Material;
        static AcidicEnrichedNaquadahSolution: Material;
        static EnrichedNaquadahWaste: Material;
        static ImpureNaquadriaSolution: Material;
        static NaquadriaSolution: Material;
        static AcidicNaquadriaSolution: Material;
        static NaquadriaWaste: Material;
        static Lapotron: Material;
        static UUMatter: Material;
        static PCBCoolant: Material;
        static Sculk: Material;
        static Wax: Material;
        static Glass: Material;
        static Perlite: Material;
        static Borax: Material;
        static Olivine: Material;
        static Opal: Material;
        static Amethyst: Material;
        static EchoShard: Material;
        static Lapis: Material;
        static Blaze: Material;
        static Apatite: Material;
        static BlackSteel: Material;
        static DamascusSteel: Material;
        static TungstenSteel: Material;
        static CobaltBrass: Material;
        static TricalciumPhosphate: Material;
        static GarnetRed: Material;
        static GarnetYellow: Material;
        static Marble: Material;
        static Deepslate: Material;
        static GraniteRed: Material;
        static Blackstone: Material;
        static VanadiumMagnetite: Material;
        static QuartzSand: Material;
        static Pollucite: Material;
        static Bentonite: Material;
        static FullersEarth: Material;
        static Pitchblende: Material;
        static Monazite: Material;
        static Mirabilite: Material;
        static ActivatedCarbon: Material;
        static Trona: Material;
        static Gypsum: Material;
        static Zeolite: Material;
        static Concrete: Material;
        static SteelMagnetic: Material;
        static VanadiumSteel: Material;
        static Potin: Material;
        static BorosilicateGlass: Material;
        static NaquadahAlloy: Material;
        static SulfuricNickelSolution: Material;
        static SulfuricCopperSolution: Material;
        static LeadZincSolution: Material;
        static NitrationMixture: Material;
        static DilutedSulfuricAcid: Material;
        static DilutedHydrochloricAcid: Material;
        static Flint: Material;
        static Air: Material;
        static LiquidAir: Material;
        static NetherAir: Material;
        static LiquidNetherAir: Material;
        static EnderAir: Material;
        static LiquidEnderAir: Material;
        static AquaRegia: Material;
        static SaltWater: Material;
        static Clay: Material;
        static Redstone: Material;
        static Dichloroethane: Material;
        static Diethylenetriamine: Material;
        static Electrotine: Material;
        static EnderEye: Material;
        static Diatomite: Material;
        static RedSteel: Material;
        static BlueSteel: Material;
        static Basalt: Material;
        static GraniticMineralSand: Material;
        static Redrock: Material;
        static GarnetSand: Material;
        static HSSG: Material;
        static IridiumMetalResidue: Material;
        static Granite: Material;
        static Brick: Material;
        static Fireclay: Material;
        static Diorite: Material;
        static RedAlloy: Material;
        static BlueAlloy: Material;
        static BasalticMineralSand: Material;
        static HSSE: Material;
        static HSSS: Material;
        static RadAway: Material;
        static TantalumCarbide: Material;
        static HSLASteel: Material;
        static MolybdenumDisilicide: Material;
        static Zeron100: Material;
        static WatertightSteel: Material;
        static IncoloyMA956: Material;
        static MaragingSteel300: Material;
        static HastelloyX: Material;
        static Stellite100: Material;
        static TitaniumCarbide: Material;
        static TitaniumTungstenCarbide: Material;
        static HastelloyC276: Material;
    }

    import Element = api.data.chemical.Element;

    class GTElements {
        static H: Element;
        static D: Element;
        static T: Element;
        static He: Element;
        static He3: Element;
        static Li: Element;
        static Be: Element;
        static B: Element;
        static C: Element;
        static N: Element;
        static O: Element;
        static F: Element;
        static Ne: Element;
        static Na: Element;
        static Mg: Element;
        static Al: Element;
        static Si: Element;
        static P: Element;
        static S: Element;
        static Cl: Element;
        static Ar: Element;
        static K: Element;
        static Ca: Element;
        static Sc: Element;
        static Ti: Element;
        static V: Element;
        static Cr: Element;
        static Mn: Element;
        static Fe: Element;
        static Co: Element;
        static Ni: Element;
        static Cu: Element;
        static Zn: Element;
        static Ga: Element;
        static Ge: Element;
        static As: Element;
        static Se: Element;
        static Br: Element;
        static Kr: Element;
        static Rb: Element;
        static Sr: Element;
        static Y: Element;
        static Zr: Element;
        static Nb: Element;
        static Mo: Element;
        static Tc: Element;
        static Ru: Element;
        static Rh: Element;
        static Pd: Element;
        static Ag: Element;
        static Cd: Element;
        static In: Element;
        static Sn: Element;
        static Sb: Element;
        static Te: Element;
        static I: Element;
        static Xe: Element;
        static Cs: Element;
        static Ba: Element;
        static La: Element;
        static Ce: Element;
        static Pr: Element;
        static Nd: Element;
        static Pm: Element;
        static Sm: Element;
        static Eu: Element;
        static Gd: Element;
        static Tb: Element;
        static Dy: Element;
        static Ho: Element;
        static Er: Element;
        static Tm: Element;
        static Yb: Element;
        static Lu: Element;
        static Hf: Element;
        static Ta: Element;
        static W: Element;
        static Re: Element;
        static Os: Element;
        static Ir: Element;
        static Pt: Element;
        static Au: Element;
        static Hg: Element;
        static Tl: Element;
        static Pb: Element;
        static Bi: Element;
        static Po: Element;
        static At: Element;
        static Rn: Element;
        static Fr: Element;
        static Ra: Element;
        static Ac: Element;
        static Th: Element;
        static Pa: Element;
        static U: Element;
        static U238: Element;
        static U235: Element;
        static Np: Element;
        static Pu: Element;
        static Pu239: Element;
        static Pu241: Element;
        static Am: Element;
        static Cm: Element;
        static Bk: Element;
        static Cf: Element;
        static Es: Element;
        static Fm: Element;
        static Md: Element;
        static No: Element;
        static Lr: Element;
        static Rf: Element;
        static Db: Element;
        static Sg: Element;
        static Bh: Element;
        static Hs: Element;
        static Mt: Element;
        static Ds: Element;
        static Rg: Element;
        static Cn: Element;
        static Nh: Element;
        static Fl: Element;
        static Mc: Element;
        static Lv: Element;
        static Ts: Element;
        static Og: Element;
        static Tr: Element;
        static Dr: Element;
        static Ke: Element;
        static Nq: Element;
        static Nq1: Element;
        static Nq2: Element;
        static Nt: Element;
        static Sp: Element;
        static Ma: Element;

        static get(name: string): Element;
    }

    import GTRecipeType = api.recipe.GTRecipeType;

    class GTRecipeTypes {
        static STEAM: string;
        static ELECTRIC: string;
        static GENERATOR: string;
        static MULTIBLOCK: string;
        static DUMMY: string;

        static STEAM_BOILER_RECIPES: GTRecipeType;
        static FURNACE_RECIPES: GTRecipeType;
        static BLAST_FURNACE_RECIPES: GTRecipeType;
        static SMOKING_FURNACE_RECIPES: GTRecipeType;
        static ALLOY_SMELTER_RECIPES: GTRecipeType;
        static ARC_FURNACE_RECIPES: GTRecipeType;
        static ASSEMBLER_RECIPES: GTRecipeType;
        static AUTOCLAVE_RECIPES: GTRecipeType;
        static BENDER_RECIPES: GTRecipeType;
        static BREWING_RECIPES: GTRecipeType;
        static MACERATOR_RECIPES: GTRecipeType;
        static CANNER_RECIPES: GTRecipeType;
        static CENTRIFUGE_RECIPES: GTRecipeType;
        static CHEMICAL_BATH_RECIPES: GTRecipeType;
        static CHEMICAL_RECIPES: GTRecipeType;
        static COMPRESSOR_RECIPES: GTRecipeType;
        static CUTTER_RECIPES: GTRecipeType;
        static DISTILLERY_RECIPES: GTRecipeType;
        static ELECTROLYZER_RECIPES: GTRecipeType;
        static ELECTROMAGNETIC_SEPARATOR_RECIPES: GTRecipeType;
        static EXTRACTOR_RECIPES: GTRecipeType;
        static EXTRUDER_RECIPES: GTRecipeType;
        static FERMENTING_RECIPES: GTRecipeType;
        static FLUID_HEATER_RECIPES: GTRecipeType;
        static FLUID_SOLIDFICATION_RECIPES: GTRecipeType;
        static FORGE_HAMMER_RECIPES: GTRecipeType;
        static FORMING_PRESS_RECIPES: GTRecipeType;
        static LATHE_RECIPES: GTRecipeType;
        static MIXER_RECIPES: GTRecipeType;
        static ORE_WASHER_RECIPES: GTRecipeType;
        static PACKER_RECIPES: GTRecipeType;
        static POLARIZER_RECIPES: GTRecipeType;
        static LASER_ENGRAVER_RECIPES: GTRecipeType;
        static SIFTER_RECIPES: GTRecipeType;
        static THERMAL_CENTRIFUGE_RECIPES: GTRecipeType;
        static WIREMILL_RECIPES: GTRecipeType;
        static CIRCUIT_ASSEMBLER_RECIPES: GTRecipeType;
        static GAS_COLLECTOR_RECIPES: GTRecipeType;
        static AIR_SCRUBBER_RECIPES: GTRecipeType;
        static ROCK_BREAKER_RECIPES: GTRecipeType;
        static COMBUSTION_GENERATOR_FUELS: GTRecipeType;
        static GAS_TURBINE_FUELS: GTRecipeType;
        static STEAM_TURBINE_FUELS: GTRecipeType;
        static PLASMA_GENERATOR_FUELS: GTRecipeType;
        static LARGE_BOILER_RECIPES: GTRecipeType;
        static COKE_OVEN_RECIPES: GTRecipeType;
        static PRIMITIVE_BLAST_FURNACE_RECIPES: GTRecipeType;
        static BLAST_RECIPES: GTRecipeType;
        static DISTILLATION_RECIPES: GTRecipeType;
        static PYROLYSE_RECIPES: GTRecipeType;
        static CRACKING_RECIPES: GTRecipeType;
        static IMPLOSION_RECIPES: GTRecipeType;
        static VACUUM_RECIPES: GTRecipeType;
        static ASSEMBLY_LINE_RECIPES: GTRecipeType;

        static get(name: string): GTRecipeType;
    }

    import RecipeModifier = internal.com.gregtechceu.gtceu.api.recipe.modifier.RecipeModifier;

    class GTRecipeModifiers {
        static OC_PERFECT: RecipeModifier;
        static OC_NON_PERFECT: RecipeModifier;
        static OC_PERFECT_SUBTICK: RecipeModifier;
        static OC_NON_PERFECT_SUBTICK: RecipeModifier;
        static OC_PERFDEFAULT_ENVIRONMENT_REQUIREMENTECT: RecipeModifier;
        static PARALLEL_HATCH: RecipeModifier;
        static BATCH_MODE: RecipeModifier;
        static CRACKER_OVERCLOCK: RecipeModifier;
        static EBF_OVERCLOCK: RecipeModifier;
        static PYROLYSE_OVEN_OVERCLOCK: RecipeModifier;
        static MULTI_SMELTER_PARALLEL: RecipeModifier;
        static CHEMICAL_REACTOR_OVERCLOCK: RecipeModifier;
        static CONSUME_EU_TO_START: RecipeModifier;
        static FUSION_OVERCLOCK: RecipeModifier;
    }

    import SoundEntry = internal.com.gregtechceu.gtceu.api.sound.SoundEntry;

    class GTSoundEntries {
        static FORGE_HAMMER: SoundEntry;
        static MACERATOR: SoundEntry;
        static CHEMICAL: SoundEntry;
        static ASSEMBLER: SoundEntry;
        static CENTRIFUGE: SoundEntry;
        static COMPRESSOR: SoundEntry;
        static ELECTROLYZER: SoundEntry;
        static MIXER: SoundEntry;
        static REPLICATOR: SoundEntry;
        static ARC: SoundEntry;
        static BOILER: SoundEntry;
        static FURNACE: SoundEntry;
        static COOLING: SoundEntry;
        static FIRE: SoundEntry;
        static BATH: SoundEntry;
        static MOTOR: SoundEntry;
        static CUT: SoundEntry;
        static TURBINE: SoundEntry;
        static COMBUSTION: SoundEntry;
        static COMPUTATION: SoundEntry;
        static MINER: SoundEntry;
        static SCIENCE: SoundEntry;
        static JET_ENGINE: SoundEntry;
        static WRENCH_TOOL: SoundEntry;
        static SOFT_MALLET_TOOL: SoundEntry;
        static DRILL_TOOL: SoundEntry;
        static PLUNGER_TOOL: SoundEntry;
        static FILE_TOOL: SoundEntry;
        static SAW_TOOL: SoundEntry;
        static SCREWDRIVER_TOOL: SoundEntry;
        static CHAINSAW_TOOL: SoundEntry;
        static WIRECUTTER_TOOL: SoundEntry;
        static SPRAY_CAN_TOOL: SoundEntry;
        static PORTABLE_SCANNER: SoundEntry;
        static MORTAR_TOOL: SoundEntry;
        static SUS_RECORD: SoundEntry;
        static PORTAL_OPENING: SoundEntry;
        static PORTAL_CLOSING: SoundEntry;
        static METAL_PIPE: SoundEntry;
    }

    import Block = internal.net.minecraft.world.level.block.Block;
    import BlockEntry = internal.com.tterrag.registrate.util.entry.BlockEntry;

    class GCYMBlocks {
        static CASING_NONCONDUCTING: BlockEntry<Block>;
        static CASING_VIBRATION_SAFE: BlockEntry<Block>;
        static CASING_WATERTIGHT: BlockEntry<Block>;
        static CASING_SECURE_MACERATION: BlockEntry<Block>;
        static CASING_HIGH_TEMPERATURE_SMELTING: BlockEntry<Block>;
        static CASING_LASER_SAFE_ENGRAVING: BlockEntry<Block>;
        static CASING_LARGE_SCALE_ASSEMBLING: BlockEntry<Block>;
        static CASING_SHOCK_PROOF: BlockEntry<Block>;
        static CASING_STRESS_PROOF: BlockEntry<Block>;
        static CASING_CORROSION_PROOF: BlockEntry<Block>;
        static CASING_REACTION_SAFE: BlockEntry<Block>;
        static CASING_ATOMIC: BlockEntry<Block>;
        static CASING_INDUSTRIAL_STEAM: BlockEntry<Block>;
        static SLICING_BLADES: BlockEntry<ActiveBlock>;
        static MOLYBDENUM_DISILICIDE_COIL_BLOCK: BlockEntry<ActiveBlock>;
        static ELECTROLYTIC_CELL: BlockEntry<ActiveBlock>;
        static CRUSHING_WHEELS: BlockEntry<ActiveBlock>;
        static HEAT_VENT: BlockEntry<ActiveBlock>;
    }

    class GTBlocks {
        static CASING_WOOD_WALL: BlockEntry<Block>;
        static CASING_COKE_BRICKS: BlockEntry<Block>;
        static CASING_PRIMITIVE_BRICKS: BlockEntry<Block>;
        static CASING_BRONZE_BRICKS: BlockEntry<Block>;
        static CASING_INVAR_HEATPROOF: BlockEntry<Block>;
        static CASING_ALUMINIUM_FROSTPROOF: BlockEntry<Block>;
        static CASING_STEEL_SOLID: BlockEntry<Block>;
        static CASING_STAINLESS_CLEAN: BlockEntry<Block>;
        static CASING_TITANIUM_STABLE: BlockEntry<Block>;
        static CASING_TUNGSTENSTEEL_ROBUST: BlockEntry<Block>;
        static CASING_PTFE_INERT: BlockEntry<Block>;
        static CASING_HSSE_STURDY: BlockEntry<Block>;
        static CASING_PALLADIUM_SUBSTATION: BlockEntry<Block>;
        static CASING_GRATE: BlockEntry<Block>;
        static CASING_ASSEMBLY_CONTROL: BlockEntry<Block>;
        static CASING_BRONZE_GEARBOX: BlockEntry<Block>;
        static CASING_STEEL_GEARBOX: BlockEntry<Block>;
        static CASING_STAINLESS_STEEL_GEARBOX: BlockEntry<Block>;
        static CASING_TITANIUM_GEARBOX: BlockEntry<Block>;
        static CASING_TUNGSTENSTEEL_GEARBOX: BlockEntry<Block>;
        static CASING_STEEL_TURBINE: BlockEntry<Block>;
        static CASING_TITANIUM_TURBINE: BlockEntry<Block>;
        static CASING_STAINLESS_TURBINE: BlockEntry<Block>;
        static CASING_TUNGSTENSTEEL_TURBINE: BlockEntry<Block>;
        static CASING_BRONZE_PIPE: BlockEntry<Block>;
        static CASING_STEEL_PIPE: BlockEntry<Block>;
        static CASING_TITANIUM_PIPE: BlockEntry<Block>;
        static CASING_TUNGSTENSTEEL_PIPE: BlockEntry<Block>;
        static CASING_POLYTETRAFLUOROETHYLENE_PIPE: BlockEntry<Block>;
        static CASING_PUMP_DECK: BlockEntry<Block>;
        static MACHINE_CASING_ULV: BlockEntry<Block>;
        static MACHINE_CASING_LV: BlockEntry<Block>;
        static MACHINE_CASING_MV: BlockEntry<Block>;
        static MACHINE_CASING_HV: BlockEntry<Block>;
        static MACHINE_CASING_EV: BlockEntry<Block>;
        static MACHINE_CASING_IV: BlockEntry<Block>;
        static MACHINE_CASING_LuV: BlockEntry<Block>;
        static MACHINE_CASING_ZPM: BlockEntry<Block>;
        static MACHINE_CASING_UV: BlockEntry<Block>;
        static MACHINE_CASING_UHV: BlockEntry<Block>;
        static MACHINE_CASING_UEV: BlockEntry<Block>;
        static MACHINE_CASING_UIV: BlockEntry<Block>;
        static MACHINE_CASING_UXV: BlockEntry<Block>;
        static MACHINE_CASING_OpV: BlockEntry<Block>;
        static MACHINE_CASING_MAX: BlockEntry<Block>;
        static HERMETIC_CASING_LV: BlockEntry<Block>;
        static HERMETIC_CASING_MV: BlockEntry<Block>;
        static HERMETIC_CASING_HV: BlockEntry<Block>;
        static HERMETIC_CASING_EV: BlockEntry<Block>;
        static HERMETIC_CASING_IV: BlockEntry<Block>;
        static HERMETIC_CASING_LuV: BlockEntry<Block>;
        static HERMETIC_CASING_ZPM: BlockEntry<Block>;
        static HERMETIC_CASING_UV: BlockEntry<Block>;
        static HERMETIC_CASING_UHV: BlockEntry<Block>;
        static BRONZE_HULL: BlockEntry<Block>;
        static BRONZE_BRICKS_HULL: BlockEntry<Block>;
        static STEEL_HULL: BlockEntry<Block>;
        static STEEL_BRICKS_HULL: BlockEntry<Block>;
        static PLASTCRETE: BlockEntry<Block>;
        static FILTER_CASING: BlockEntry<Block>;
        static FILTER_CASING_STERILE: BlockEntry<Block>;
        static FIREBOX_BRONZE: BlockEntry<ActiveBlock>;
        static FIREBOX_STEEL: BlockEntry<ActiveBlock>;
        static FIREBOX_TITANIUM: BlockEntry<ActiveBlock>;
        static FIREBOX_TUNGSTENSTEEL: BlockEntry<ActiveBlock>;
        static COMPUTER_CASING: BlockEntry<Block>;
        static ADVANCED_COMPUTER_CASING: BlockEntry<Block>;
        static COMPUTER_HEAT_VENT: BlockEntry<Block>;
        static HIGH_POWER_CASING: BlockEntry<Block>;
        static RUBBER_PLANK: BlockEntry<Block>;
        static TREATED_WOOD_PLANK: BlockEntry<Block>;
        static ACID_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static ANTIMATTER_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static BIO_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static BOSS_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static CAUSALITY_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static EXPLOSION_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static FIRE_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static FROST_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static GENERIC_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static GREGIFICATION_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static HIGH_PRESSURE_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static HIGH_VOLTAGE_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static HIGH_TEMPERATURE_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static LASER_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static MAGIC_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static MAGNETIC_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static MOB_INFESTATION_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static MOB_SPAWNER_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static NOISE_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static RADIOACTIVE_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static SPATIAL_STORAGE_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static TURRET_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static VOID_HAZARD_SIGN_BLOCK: BlockEntry<Block>;
        static YELLOW_STRIPES_BLOCK_A: BlockEntry<Block>;
        static YELLOW_STRIPES_BLOCK_B: BlockEntry<Block>;
        static PETRIFIED_FOAM: BlockEntry<Block>;
        static REINFORCED_STONE: BlockEntry<Block>;
    }
}

namespace internal.com.gregtechceu.gtceu.common.data.machines {
    import MachineDefinition = api.machine.MachineDefinition;
    import MultiblockMachineDefinition = api.machine.MultiblockMachineDefinition;

    class GCYMMachines {
        static PARALLEL_HATCH: MachineDefinition[];
        static LARGE_MACERATION_TOWER: MultiblockMachineDefinition;
        static LARGE_CHEMICAL_BATH: MultiblockMachineDefinition;
        static LARGE_CENTRIFUGE: MultiblockMachineDefinition;
        static LARGE_MIXER: MultiblockMachineDefinition;
        static LARGE_ELECTROLYZER: MultiblockMachineDefinition;
        static LARGE_ELECTROMAGNET: MultiblockMachineDefinition;
        static LARGE_PACKER: MultiblockMachineDefinition;
        static LARGE_ASSEMBLER: MultiblockMachineDefinition;
        static LARGE_CIRCUIT_ASSEMBLER: MultiblockMachineDefinition;
        static LARGE_ARC_SMELTER: MultiblockMachineDefinition;
        static LARGE_ENGRAVING_LASER: MultiblockMachineDefinition;
        static LARGE_SIFTING_FUNNEL: MultiblockMachineDefinition;
        static BLAST_ALLOY_SMELTER: MultiblockMachineDefinition;
        static LARGE_AUTOCLAVE: MultiblockMachineDefinition;
        static LARGE_MATERIAL_PRESS: MultiblockMachineDefinition;
        static LARGE_BREWER: MultiblockMachineDefinition;
        static LARGE_CUTTER: MultiblockMachineDefinition;
        static LARGE_DISTILLERY: MultiblockMachineDefinition;
        static LARGE_EXTRACTOR: MultiblockMachineDefinition;
        static LARGE_EXTRUDER: MultiblockMachineDefinition;
        static LARGE_SOLIDIFIER: MultiblockMachineDefinition;
        static LARGE_WIREMILL: MultiblockMachineDefinition;
        static MEGA_BLAST_FURNACE: MultiblockMachineDefinition;
        static MEGA_VACUUM_FREEZER: MultiblockMachineDefinition;
    }
}

namespace internal.com.gregtechceu.gtceu.common.machine.multiblock.part {
    import IMachineBlockEntity = api.machine.IMachineBlockEntity;
    import TieredIOPartMachine = api.machine.multiblock.part.TieredIOPartMachine;
    import IO__Wrapper = internal.com.gregtechceu.gtceu.api.capability.recipe.IO__Wrapper;

    class FluidHatchPartMachine extends TieredIOPartMachine {
        constructor(
            holder: IMachineBlockEntity,
            tier: number,
            io: IO__Wrapper,
            initialCapacity: number,
            slots: number,
            ...args: unknown[]
        );
        constructor(
            holder: IMachineBlockEntity,
            tier: number,
            io: IO__Wrapper,
            initialCapacity: number,
            slots: number,
            args: unknown[]
        );
    }

    import TieredPartMachine = api.machine.multiblock.part.TieredPartMachine;
    class AutoMaintenanceHatchPartMachine extends TieredPartMachine {}

    class CleaningMaintenanceHatchPartMachine extends AutoMaintenanceHatchPartMachine {
        constructor(holder: IMachineBlockEntity, cleanroomType: CleanroomType);
    }
}

namespace internal.com.gregtechceu.gtceu.common.machine.multiblock.generator {
    import WorkableElectricMultiblockMachine = api.machine.multiblock.WorkableElectricMultiblockMachine;
    import IMachineBlockEntity = api.machine.IMachineBlockEntity;

    class LargeTurbineMachine extends WorkableElectricMultiblockMachine {
        constructor(holder: IMachineBlockEntity, tier: number);
    }
}

namespace internal.com.gregtechceu.gtceu.common.machine.multiblock.steam {
    import IMachineBlockEntity = api.machine.IMachineBlockEntity;
    import WorkableElectricMultiblockMachine = api.machine.multiblock.WorkableElectricMultiblockMachine;
    import MetaMachine = api.machine.MetaMachine;
    import GTRecipe = api.recipe.GTRecipe;
    import ModifierFunction = api.recipe.modifier.ModifierFunction;

    class SteamParallelMultiblockMachine extends WorkableElectricMultiblockMachine {
        constructor(holder: IMachineBlockEntity, args: any[]);
        constructor(holder: IMachineBlockEntity, ...args: any[]);

        static recipeModifier(machine: MetaMachine, recipe: GTRecipe): ModifierFunction;
    }
}

namespace internal.com.gregtechceu.gtceu.common.machine.multiblock.electric {
    import WorkableElectricMultiblockMachine = api.machine.multiblock.WorkableElectricMultiblockMachine;
    import IMachineBlockEntity = api.machine.IMachineBlockEntity;
    import IMachineBlockEntity = java.util.Comparator;
    import MultiblockControllerMachine = api.machine.multiblock.MultiblockControllerMachine;

    class AssemblyLineMachine extends WorkableElectricMultiblockMachine {
        constructor(holder: IMachineBlockEntity, allowCircuitSlots: boolean);
        constructor(holder: IMachineBlockEntity);

        static partSorter(mc: MultiblockControllerMachine): Comparator<IMultiPart>;
    }
}

namespace internal.com.gregtechceu.gtceu.common.machine.multiblock.electric.research {
    import WorkableElectricMultiblockMachine = api.machine.multiblock.WorkableElectricMultiblockMachine;
    import IMachineBlockEntity = api.machine.IMachineBlockEntity;

    class OpticalComputationMachine extends WorkableElectricMultiblockMachine {
        constructor(holder: IMachineBlockEntity, ...args: any[]);
    }
}

namespace internal.kjs {
    interface LoadableClasses {
        'com.gregtechceu.gtceu.common.machine.multiblock.steam.SteamParallelMultiblockMachine': typeof internal.com.gregtechceu.gtceu.common.machine.multiblock.steam.SteamParallelMultiblockMachine;
        'com.gregtechceu.gtceu.common.machine.multiblock.electric.research.OpticalComputationMachine': typeof internal.com.gregtechceu.gtceu.common.machine.multiblock.electric.research.OpticalComputationMachine;
        'com.gregtechceu.gtceu.common.machine.multiblock.electric.AssemblyLineMachine': typeof internal.com.gregtechceu.gtceu.common.machine.multiblock.electric.AssemblyLineMachine;
        'com.gregtechceu.gtceu.common.machine.multiblock.part.FluidHatchPartMachine': typeof internal.com.gregtechceu.gtceu.common.machine.multiblock.part.FluidHatchPartMachine;
        'com.gregtechceu.gtceu.common.machine.multiblock.part.CleaningMaintenanceHatchPartMachine': typeof internal.com.gregtechceu.gtceu.common.machine.multiblock.part.CleaningMaintenanceHatchPartMachine;
    }
}
